### ISSUE TITLE
Memory.cpp is missing

### ISSUE THREAD

**Issue by adelinn** [SystematicSkid/AgeOfEmpires#1]
Memory.cpp file is missing, but it is included in the project file.
Can you check if you still have it? It's been a long time since 2018... :) but the game is regaining popularity.

**Comment by SystematicSkid** [comment]
Hey, I think the only important function in Memory.cpp was the signature scanner, and you can find those anywhere.
Regardless, I have rewritten this SDK entirely and I streamed a very large majority of it, the VODS are still on my youtube channel if you would like to see, but I'm not sure if I'll be uploading the full source on Git since it could be used commercially and someone is likely to try to profit off my work.

**Comment by adelinn** [comment]
What's your YT channel?

**Comment by SystematicSkid** [comment]
https://www.youtube.com/channel/UCURlLFu-G-W-0kFS-qfNqHQ

**Comment by adelinn** [comment]
Thanks. I'll close this issue.
